# Generated by Django 4.2.6 on 2023-10-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessedText',
            new_name='TextPassage',
        ),
    ]
