# Generated by Django 4.2.6 on 2023-10-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_rename_processedtext_textpassage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='TextPassage',
        ),
    ]
