# Generated by Django 4.2.6 on 2023-10-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_alter_qadata_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
