# Generated by Django 4.2.6 on 2023-10-23 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_processedtext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedText',
        ),
    ]
