# Generated by Django 4.2.6 on 2023-10-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_delete_processedtext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qadata',
            old_name='answer',
            new_name='answer1',
        ),
        migrations.RenameField(
            model_name='qadata',
            old_name='question',
            new_name='answer2',
        ),
        migrations.AddField(
            model_name='qadata',
            name='answer3',
            field=models.TextField(default='Default Answer for Question 3'),
        ),
        migrations.AddField(
            model_name='qadata',
            name='answer4',
            field=models.TextField(default='Default Answer for Question 4'),
        ),
        migrations.AddField(
            model_name='qadata',
            name='answer5',
            field=models.TextField(default='Default Answer for Question 5'),
        ),
        migrations.AddField(
            model_name='qadata',
            name='question1',
            field=models.CharField(default='Default Answer for Question 1', max_length=255),
        ),
        migrations.AddField(
            model_name='qadata',
            name='question2',
            field=models.CharField(default='Default Answer for Question 2', max_length=255),
        ),
        migrations.AddField(
            model_name='qadata',
            name='question3',
            field=models.CharField(default='Default Answer for Question 3', max_length=255),
        ),
        migrations.AddField(
            model_name='qadata',
            name='question4',
            field=models.CharField(default='Default Answer for Question 4', max_length=255),
        ),
        migrations.AddField(
            model_name='qadata',
            name='question5',
            field=models.CharField(default='Default Answer for Question 5', max_length=255),
        ),
        migrations.AddField(
            model_name='qadata',
            name='sentiment_polarity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qadata',
            name='sentiment_subjectivity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
