# Generated by Django 4.2.6 on 2023-10-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0008_alter_qadata_answer3_alter_qadata_answer4_and_more'),
    ]

    operations = [
    ]


"""from django.db import migrations, models
from yourapp.models import YourModel

def update_data(apps, schema_editor):
    YourModel = apps.get_model('yourapp', 'YourModel')
    for obj in YourModel.objects.all():
        obj.new_field = transform_data(obj.old_field)
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('yourapp', 'previous_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='new_field',
            field=models.CharField(max_length=255),
        ),
        migrations.RunPython(update_data),
    ]
"""